
#building and adding kubectl
FROM alpine:3.8 as kubectl

ADD https://storage.googleapis.com/kubernetes-release/release/v1.6.4/bin/linux/amd64/kubectl /usr/local/bin/kubectl
ENV HOME=/config \
    KUBECONFIG=/etc/kubernetes/admin.conf
RUN set -x && \
    apk add --no-cache curl ca-certificates && \
    chmod +x /usr/local/bin/kubectl

#your app container
FROM armadak8s/armada:latest

COPY --from=kubectl /usr/local/bin/kubectl /usr/local/bin/kubectl